export const CATEGORIES = [
  { slug: "gut-health", label: "Gut Health" },
  { slug: "weight-management", label: "Weight Management" },
  { slug: "skin-health", label: "Skin Health" },
  { slug: "active-lifestyle", label: "Active Lifestyle" },
  { slug: "general-nutrition", label: "General Nutrition" },
  { slug: "womens-health", label: "Women's Health" },
  { slug: "family-nutrition", label: "Family Nutrition" },
  { slug: "combos", label: "Combos" },
] as const;

export type CategorySlug = (typeof CATEGORIES)[number]["slug"];

export type Product = {
  slug: string;
  name: string;
  sku: string;
  category: CategorySlug;
  retail: number;
  vip: number;
  pv: number;
  vipPv: number;
  image: string;
  badge?: string;
  topSeller?: boolean;
  optionsNote?: string;
  blurb: string;
  benefits: string[];
  included?: string[];
  form: string;
  glutenFree?: boolean;
  vegetarian?: boolean;
  nonGmo?: boolean;
  featured?: boolean;
  kind: "product" | "combo";
};

const I = {
  gut: "/plexus/gut-health.png",
  glp: "/plexus/glp1.png",
  skin: "/plexus/skin-health.png",
  mega: "/plexus/megax-bottles.jpg",
  slim: "/plexus/slim-pink.jpg",
  kit: "/plexus/gut-kit.jpg",
  super: "/plexus/superfoods.jpg",
  skinSet: "/plexus/skincare-set.jpg",
  active: "/plexus/active-lean.jpg",
  caps: "/plexus/capsules.jpg",
  hyd: "/plexus/hydrate.jpg",
  kids: "/plexus/kids.jpg",
  promo: "/plexus/promo-box.png",
};

export const products: Product[] = [
  {
    slug: "glp-1-support-system",
    name: "GLP-1 Support System",
    sku: "K1-GLP1-0001",
    category: "weight-management",
    retail: 235,
    vip: 181,
    pv: 181,
    vipPv: 140,
    image: I.glp,
    badge: "Top Seller",
    topSeller: true,
    featured: true,
    kind: "combo",
    form: "System",
    glutenFree: true,
    nonGmo: true,
    blurb: "A targeted system designed to complement your wellness routine with microbiome, satiety, and metabolic support from the inside out.",
    benefits: [
      "Supports healthy glucose metabolism*",
      "Helps curb hunger so you feel satisfied longer*",
      "Feeds beneficial gut microbes with clinically studied prebiotics*",
      "Pairs clean nutrition with daily microbiome care*",
    ],
    included: ["Slim Hunger Control or Slim Microbiome Activating", "MetaBurn", "Restore", "Hydrate"],
  },
  {
    slug: "gut-health-system-bio-cleanse-60",
    name: "Gut Health System – Bio Cleanse® 60",
    sku: "K1-GHS-0060",
    category: "gut-health",
    retail: 163,
    vip: 126,
    pv: 142,
    vipPv: 110,
    image: I.gut,
    badge: "Top Seller",
    topSeller: true,
    featured: true,
    optionsNote: "Slim options available",
    kind: "combo",
    form: "System",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "The foundational 3-step microbiome system: cleanse, feed, and seed — with Bio Cleanse® 60, Slim, and a daily probiotic.",
    benefits: [
      "Helps cleanse the digestive tract*",
      "Clinically demonstrated to help you lose weight with Slim*",
      "Promotes the growth of beneficial gut microbes*",
      "Patented formula for improving gut health (U.S. Patent No. 11730749)*",
    ],
    included: ["Bio Cleanse® 60 capsules", "30 packets of Slim (Microbiome Activating or Hunger Control)", "ProBio 5® or VitalBiome®"],
  },
  {
    slug: "gut-health-system-bio-cleanse-120",
    name: "Gut Health System – Bio Cleanse® 120",
    sku: "K1-GHS-0120",
    category: "gut-health",
    retail: 176,
    vip: 137,
    pv: 154,
    vipPv: 120,
    image: I.gut,
    topSeller: true,
    optionsNote: "Slim options available",
    kind: "combo",
    form: "System",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "The same microbiome-first Gut Health System with a larger Bio Cleanse® supply for continued daily support.",
    benefits: [
      "Daily digestive cleanse support*",
      "Feeds the microbiome with XOS prebiotic Slim*",
      "Convenient system packaging for a complete routine*",
    ],
    included: ["Bio Cleanse® 120 capsules", "30 packets of Slim", "Daily probiotic"],
  },
  {
    slug: "skin-health-system",
    name: "Plexus® Skin Health System",
    sku: "K1-SKIN-0001",
    category: "skin-health",
    retail: 186,
    vip: 139,
    pv: 147,
    vipPv: 110,
    image: I.skin,
    featured: true,
    kind: "combo",
    form: "System",
    glutenFree: true,
    blurb: "A complete inside-and-out ritual: cleanse, treat, protect, and nourish skin while supporting the gut-skin connection.",
    benefits: [
      "Supports the skin’s natural moisture barrier*",
      "Helps skin look smoother, brighter, and more even*",
      "Pairs topical care with collagen and microbiome support*",
    ],
    included: ["Fresh Face Refreshing Gel Cleanser", "Glow Getter Youth Renewal Serum", "After Hours Restorative Night Cream", "Sun Shield Hydrating Mineral Sunscreen"],
  },
  {
    slug: "gut-health-armor-combo",
    name: "Gut Health System & Armor Combo",
    sku: "K1-GHA-0001",
    category: "gut-health",
    retail: 204,
    vip: 156,
    pv: 170,
    vipPv: 130,
    image: I.kit,
    kind: "combo",
    form: "Combo",
    glutenFree: true,
    nonGmo: true,
    blurb: "The Gut Health System plus Plexus Armor™ to support, enhance, and fortify the gut’s protective lining.",
    benefits: [
      "Foundational microbiome care plus gut-barrier support*",
      "Bioactive-rich A2 colostrum for immune health*",
      "Mixes smoothly into Slim, coffee, or water*",
    ],
    included: ["Gut Health System – Bio Cleanse® 60", "Plexus Armor™ (30 servings)"],
  },
  {
    slug: "slim-xfactor-vitalbiome-combo",
    name: "Plexus Slim®, XFactor Plus® & VitalBiome™ Combo",
    sku: "K1-DNCM-0206",
    category: "gut-health",
    retail: 179,
    vip: 139,
    pv: 155,
    vipPv: 120,
    image: I.slim,
    optionsNote: "Slim options available",
    kind: "combo",
    form: "Combo",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Revitalize your health with prebiotics, probiotics, and essential vitamins and minerals in one convenient pairing.",
    benefits: [
      "Clinically demonstrated to help you lose weight with Slim*",
      "XFactor+ delivers a daily micronutrient foundation*",
      "VitalBiome supports mood, digestion, and microbiome balance*",
    ],
    included: ["30 packets of Slim", "60 capsules of XFactor+", "30 capsules of VitalBiome"],
  },
  {
    slug: "reset",
    name: "Plexus Reset™",
    sku: "P1-RSET-0001",
    category: "weight-management",
    retail: 159,
    vip: 119,
    pv: 134,
    vipPv: 100,
    image: I.kit,
    badge: "3-Day Reset",
    kind: "product",
    form: "3-day program",
    glutenFree: true,
    blurb: "Reset your metabolism, cravings, and gut — and lose up to 6 lbs in 3 days with a nutritionally supported fast.^",
    benefits: [
      "Participants lost up to 6 pounds over 3 days^",
      "1% reduction in body fat, primarily from fat rather than water^",
      "Supports hydration, hunger, energy, nutrition, and digestion*",
    ],
    included: ["Hydrate", "Slim Hunger Control", "Active", "Lean", "Smart Snack", "Restore"],
  },
  {
    slug: "megax",
    name: "Plexus MegaX®",
    sku: "P1-MXSG-X60D",
    category: "general-nutrition",
    retail: 47,
    vip: 35,
    pv: 38,
    vipPv: 28,
    image: I.mega,
    badge: "Better for you",
    featured: true,
    kind: "product",
    form: "60 softgels",
    glutenFree: true,
    nonGmo: true,
    blurb: "A plant-based, broad-spectrum omega that supports heart, brain, eyes, and stress management — without the fishy aftertaste.",
    benefits: [
      "Supports heart health and healthy cognitive function*",
      "Helps with stress management*",
      "Supports healthy lipid levels already in the normal range*",
      "Reformulated with only beneficial seed oils, including Ahiflower® Oil*",
    ],
  },
  {
    slug: "slim-microbiome-activating",
    name: "Plexus Slim® Microbiome Activating",
    sku: "P1-SLIM-MBA",
    category: "weight-management",
    retail: 98,
    vip: 79,
    pv: 86,
    vipPv: 72,
    image: I.slim,
    topSeller: true,
    kind: "product",
    form: "30 packets",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "The original pink drink — a patented, clinically studied XOS prebiotic that helps you lose weight while feeding beneficial gut microbes.",
    benefits: [
      "Clinically demonstrated to help you lose weight*",
      "Increases Lactobacillus up to 365 times and Bifidobacterium up to 290 times◊*",
      "Increases metabolism-enhancing Akkermansia up to 250 times◊*",
      "Supports healthy glucose metabolism*",
    ],
  },
  {
    slug: "slim-hunger-control",
    name: "Plexus Slim® Hunger Control",
    sku: "P1-SLIM-HC",
    category: "weight-management",
    retail: 98,
    vip: 79,
    pv: 86,
    vipPv: 72,
    image: I.slim,
    kind: "product",
    form: "30 packets",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Clinically demonstrated to help you lose weight while helping you feel full longer with calorie-smart prebiotic fiber.",
    benefits: [
      "Helps reduce hunger and signal satiety*",
      "Supports healthy glucose metabolism*",
      "Delicious daily drink mix in multiple flavors*",
    ],
  },
  {
    slug: "armor",
    name: "Plexus Armor™",
    sku: "P1-ARMR-0001",
    category: "gut-health",
    retail: 64,
    vip: 48,
    pv: 48,
    vipPv: 36,
    image: I.super,
    kind: "product",
    form: "Canister · 30 servings",
    glutenFree: true,
    blurb: "Support, enhance, and fortify your gut’s protective lining to promote digestive comfort, immune health, and a resilient microbiome.",
    benefits: [
      "Helps offset lifestyle and age-related gut barrier decline*",
      "Bioactive-rich A2 colostrum with lactoferrin and immunoglobulins*",
      "Neutral taste — mix into Slim, coffee, smoothies, or water*",
    ],
  },
  {
    slug: "bio-cleanse-60",
    name: "Plexus Bio Cleanse® 60",
    sku: "P1-BC60-0001",
    category: "gut-health",
    retail: 27,
    vip: 19,
    pv: 23,
    vipPv: 16,
    image: I.caps,
    kind: "product",
    form: "60 capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "A gentle daily cleanse that supports digestive regularity and helps prepare the gut for microbiome-nourishing nutrition.",
    benefits: [
      "Supports digestive comfort and regularity*",
      "A foundational step in the Plexus 3-step gut health approach*",
    ],
  },
  {
    slug: "probio-5",
    name: "Plexus ProBio 5®",
    sku: "P1-PB5-0001",
    category: "gut-health",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "30 servings",
    glutenFree: true,
    nonGmo: true,
    blurb: "A targeted probiotic blend that seeds the gut with beneficial bacteria to complement Slim and Bio Cleanse.",
    benefits: [
      "Helps replenish beneficial gut bacteria*",
      "Supports digestive and immune health*",
    ],
  },
  {
    slug: "vitalbiome",
    name: "Plexus VitalBiome™",
    sku: "P1-VTBM-0001",
    category: "gut-health",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "30 capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "A mood-and-microbiome probiotic featuring Lactobacillus helveticus (Rosell-52) and Bacillus coagulans (LactoSpore®).",
    benefits: [
      "Helps enhance gut microbiome health*",
      "Supports mood and helps reduce feelings of stress and tension*",
      "Clinically studied strains for occasional GI discomfort*",
    ],
  },
  {
    slug: "superfoods",
    name: "Plexus® Superfoods",
    sku: "P1-SPFD-0001",
    category: "general-nutrition",
    retail: 63,
    vip: 47,
    pv: 44,
    vipPv: 33,
    image: I.super,
    kind: "product",
    form: "Powder · 30 servings",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "A clean, plant-based blend of 40+ superfoods — a full serving of vegetables plus antioxidants, functional mushrooms, fiber, and 70+ trace minerals.",
    benefits: [
      "Delivers a full USDA serving of vegetables in each scoop*",
      "Prebiotic fiber supports gut and microbiome health*",
      "Functional mushrooms and antioxidants for everyday stress support*",
    ],
  },
  {
    slug: "balance",
    name: "Plexus Balance®",
    sku: "P1-BAL-0001",
    category: "weight-management",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Hormone-balance support formulated to complement a microbiome-first wellness routine.",
    benefits: ["Supports healthy hormone balance already in the normal range*", "Complements Slim and the Gut Health System*"],
  },
  {
    slug: "block",
    name: "Plexus Block®",
    sku: "P1-BLK-0001",
    category: "weight-management",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Helps intercept dietary carbs and fats as part of a weight-management routine.",
    benefits: ["Supports healthy weight management*", "Pairs with Slim Hunger Control*"],
  },
  {
    slug: "edge",
    name: "Plexus Edge®",
    sku: "P1-EDG-0001",
    category: "active-lifestyle",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Nootropic support for focus, mental clarity, and everyday cognitive performance.",
    benefits: ["Supports focus and mental energy*", "Complements MegaX for brain health*"],
  },
  {
    slug: "ease-capsules",
    name: "Plexus Ease® Capsules",
    sku: "P1-EAS-0001",
    category: "general-nutrition",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Daily comfort support formulated for people who want to move through the day with less occasional joint discomfort.",
    benefits: ["Supports joint comfort and mobility*", "Plant-based formula*"],
  },
  {
    slug: "ease-cream",
    name: "Plexus Ease® Cream",
    sku: "P1-EAC-0001",
    category: "skin-health",
    retail: 42,
    vip: 32,
    pv: 34,
    vipPv: 26,
    image: I.skinSet,
    kind: "product",
    form: "Topical cream",
    blurb: "A soothing topical cream for targeted, everyday comfort.",
    benefits: ["Cools and comforts on contact*", "Easy to layer into a daily ritual*"],
  },
  {
    slug: "immune-plus",
    name: "Plexus Immune+®",
    sku: "P1-IMM-0001",
    category: "general-nutrition",
    retail: 47,
    vip: 35,
    pv: 38,
    vipPv: 28,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Daily immune support with a microbiome-aware formula for year-round resilience.",
    benefits: ["Supports healthy immune system function*", "Complements gut-first wellness*"],
  },
  {
    slug: "metaburn",
    name: "Plexus MetaBurn®",
    sku: "P1-MTB-0001",
    category: "weight-management",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Metabolic support designed to complement Slim as you work toward a healthy weight.",
    benefits: ["Supports a healthy metabolism*", "Pairs with the GLP-1 Support System*"],
  },
  {
    slug: "nerve",
    name: "Plexus Nerve®",
    sku: "P1-NRV-0001",
    category: "general-nutrition",
    retail: 51,
    vip: 38,
    pv: 42,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Nerve health support with nutrients that help you feel your best from the inside out.",
    benefits: ["Supports healthy nerve function*", "Daily capsule convenience*"],
  },
  {
    slug: "sleep",
    name: "Plexus Sleep®",
    sku: "P1-SLP-0001",
    category: "general-nutrition",
    retail: 32,
    vip: 24,
    pv: 24,
    vipPv: 18,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "A gentle nighttime formula to help you wind down and wake feeling restored.",
    benefits: ["Supports restful sleep*", "Non-habit forming nighttime ritual*"],
  },
  {
    slug: "xfactor",
    name: "Plexus XFactor®",
    sku: "P1-XF-0001",
    category: "general-nutrition",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    nonGmo: true,
    blurb: "A daily vitamin and mineral foundation to fill nutritional gaps.",
    benefits: ["Broad-spectrum micronutrient support*", "Complements a microbiome-first routine*"],
  },
  {
    slug: "xfactor-plus",
    name: "Plexus XFactor Plus®",
    sku: "P1-XFP-0001",
    category: "general-nutrition",
    retail: 51,
    vip: 38,
    pv: 41,
    vipPv: 31,
    image: I.caps,
    kind: "product",
    form: "60 capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "An enhanced daily multi with additional antioxidant and wellness support.",
    benefits: ["Daily vitamins, minerals, and antioxidants*", "A cornerstone of Plexus wellness combos*"],
  },
  {
    slug: "xfactor-kids",
    name: "Plexus XFactor Kids™",
    sku: "P1-XFK-0001",
    category: "family-nutrition",
    retail: 40,
    vip: 30,
    pv: 32,
    vipPv: 25,
    image: I.kids,
    kind: "product",
    form: "Chewable tablets",
    glutenFree: true,
    nonGmo: true,
    blurb: "Kid-friendly chewables designed to fill nutritional gaps with a taste kids actually want.",
    benefits: ["Age-appropriate daily nutrition*", "Chewable format kids enjoy*"],
  },
  {
    slug: "megakids-microbiome",
    name: "Plexus MegaKids Microbiome®",
    sku: "P1-MKM-0001",
    category: "family-nutrition",
    retail: 44,
    vip: 33,
    pv: 34,
    vipPv: 26,
    image: I.kids,
    kind: "product",
    form: "Powder",
    glutenFree: true,
    nonGmo: true,
    blurb: "Microbiome support formulated for growing kids — a family-friendly way to nourish gut health.",
    benefits: ["Supports a healthy kids’ microbiome*", "Easy to mix into drinks or food*"],
  },
  {
    slug: "hydrate",
    name: "Plexus Hydrate®",
    sku: "P1-HYD-0001",
    category: "active-lifestyle",
    retail: 42,
    vip: 32,
    pv: 33,
    vipPv: 25,
    image: I.hyd,
    kind: "product",
    form: "Drink mix",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Electrolyte hydration that keeps you refreshed, replenished, and ready — including Watermelon Lychee and classic citrus flavors.",
    benefits: ["Helps you stay refreshed and replenished*", "A Reset staple for hydration support*"],
  },
  {
    slug: "active",
    name: "Plexus Active®",
    sku: "P1-ACT-0001",
    category: "active-lifestyle",
    retail: 42,
    vip: 32,
    pv: 33,
    vipPv: 25,
    image: I.active,
    kind: "product",
    form: "15 packets",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Clean, focused energy — including Starfruit Guava — without the crash of typical energy drinks.",
    benefits: ["Provides clean, focused energy*", "Supports an active day as energy naturally dips*"],
  },
  {
    slug: "creatine-plus",
    name: "Plexus Creatine +",
    sku: "P1-CRT-0001",
    category: "active-lifestyle",
    retail: 39,
    vip: 29,
    pv: 30,
    vipPv: 22,
    image: I.active,
    kind: "product",
    form: "Powder",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Performance creatine plus supportive nutrients for strength, recovery, and an active lifestyle.",
    benefits: ["Supports strength and training performance*", "Mixes into your daily Active or water*"],
  },
  {
    slug: "lean-whey",
    name: "Plexus Lean® Whey",
    sku: "P1-LNW-0001",
    category: "weight-management",
    retail: 57,
    vip: 43,
    pv: 38,
    vipPv: 29,
    image: I.active,
    kind: "product",
    form: "Meal replacement",
    glutenFree: true,
    blurb: "A delicious meal replacement loaded with vitamins and minerals, prebiotic fiber, and digestive enzymes.",
    benefits: ["Helps maintain lean muscle mass*", "Prebiotic fiber and enzymes support digestion*"],
  },
  {
    slug: "lean-vegan",
    name: "Plexus Lean® Vegan",
    sku: "P1-LNV-0001",
    category: "weight-management",
    retail: 65,
    vip: 49,
    pv: 42,
    vipPv: 32,
    image: I.active,
    kind: "product",
    form: "Meal replacement",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Plant-based meal replacement nutrition with the same gut-friendly philosophy as Lean Whey.",
    benefits: ["Vegan protein to fuel your day*", "Supports a healthy weight-management routine*"],
  },
  {
    slug: "restore",
    name: "Plexus Restore®",
    sku: "P1-RST-0001",
    category: "gut-health",
    retail: 105,
    vip: 79,
    pv: 80,
    vipPv: 60,
    image: I.hyd,
    kind: "product",
    form: "30 packets",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Detox, digestion, and appetite support in a daily lemon-berry drink — a key piece of Reset and ongoing gut care.",
    benefits: ["Supports detox and digestion*", "Helps with appetite support during Reset*"],
  },
  {
    slug: "collagen-complex",
    name: "Multi-Action Collagen Complex",
    sku: "P1-COL-0001",
    category: "skin-health",
    retail: 66,
    vip: 50,
    pv: 55,
    vipPv: 42,
    image: I.skinSet,
    kind: "product",
    form: "Powder / capsules",
    glutenFree: true,
    blurb: "Beauty-from-within collagen support for skin elasticity, hair, and nails — a core of the Beauty From Within combo.",
    benefits: ["Supports skin elasticity and hydration from within*", "Complements the Skin Health System*"],
  },
  {
    slug: "after-hours-night-cream",
    name: "After Hours Restorative Night Cream",
    sku: "P1-AHC-0001",
    category: "skin-health",
    retail: 53,
    vip: 40,
    pv: 42,
    vipPv: 32,
    image: I.skinSet,
    kind: "product",
    form: "Night cream",
    blurb: "An overnight moisturizer that helps skin recover while you sleep.",
    benefits: ["Restores overnight moisture*", "A hero step in the Skin Health System*"],
  },
  {
    slug: "glow-getter-serum",
    name: "Glow Getter Youth Renewal Serum",
    sku: "P1-GGS-0001",
    category: "skin-health",
    retail: 80,
    vip: 60,
    pv: 64,
    vipPv: 48,
    image: I.skinSet,
    kind: "product",
    form: "Serum",
    blurb: "A concentrated serum for smoother-looking, more radiant skin.",
    benefits: ["Helps skin look renewed and luminous*", "Lightweight, layerable formula*"],
  },
  {
    slug: "fresh-face-cleanser",
    name: "Fresh Face Refreshing Gel Cleanser",
    sku: "P1-FFC-0001",
    category: "skin-health",
    retail: 31,
    vip: 23,
    pv: 26,
    vipPv: 19,
    image: I.skinSet,
    kind: "product",
    form: "Cleanser",
    blurb: "A refreshing gel cleanser that preps skin without stripping.",
    benefits: ["Gently removes daily buildup*", "The first step of the Skin Health System*"],
  },
  {
    slug: "sun-shield",
    name: "Sun Shield Hydrating Mineral Sunscreen",
    sku: "P1-SNS-0001",
    category: "skin-health",
    retail: 43,
    vip: 32,
    pv: 35,
    vipPv: 26,
    image: I.skinSet,
    kind: "product",
    form: "Mineral sunscreen",
    blurb: "Hydrating mineral sunscreen to protect the skin you just invested in.",
    benefits: ["Mineral protection with a hydrating finish*", "Daily essential for skin health*"],
  },
  {
    slug: "body-cream",
    name: "Plexus Body Cream",
    sku: "P1-BDC-0001",
    category: "skin-health",
    retail: 52,
    vip: 39,
    pv: 42,
    vipPv: 32,
    image: I.skinSet,
    kind: "product",
    form: "Body cream",
    blurb: "Rich, daily moisture for skin that feels as good as it looks.",
    benefits: ["Deep hydration for the body*", "Complements topical facial care*"],
  },
  {
    slug: "bright-eyes",
    name: "Bright Eyes Revitalizing Eye Cream",
    sku: "P1-BYE-0001",
    category: "skin-health",
    retail: 53,
    vip: 40,
    pv: 42,
    vipPv: 32,
    image: I.skinSet,
    kind: "product",
    form: "Eye cream",
    blurb: "A revitalizing eye cream to brighten the look of tired eyes.",
    benefits: ["Helps the eye area look more rested*", "Lightweight cream for morning or night*"],
  },
  {
    slug: "damage-control-mask",
    name: "Damage Control Soothing Treatment Mask",
    sku: "P1-DCM-0001",
    category: "skin-health",
    retail: 42,
    vip: 32,
    pv: 33,
    vipPv: 25,
    image: I.skinSet,
    kind: "product",
    form: "Treatment mask",
    blurb: "A soothing mask for days your skin needs extra calm and recovery.",
    benefits: ["Soothes and comforts stressed-looking skin*", "Use as a weekly treatment*"],
  },
  {
    slug: "ironwoman",
    name: "Plexus IronWoman™",
    sku: "P1-IRW-0001",
    category: "womens-health",
    retail: 27,
    vip: 19,
    pv: 23,
    vipPv: 16,
    image: I.caps,
    kind: "product",
    form: "Capsules",
    glutenFree: true,
    vegetarian: true,
    nonGmo: true,
    blurb: "Gentle iron support formulated with women in mind.",
    benefits: ["Supports healthy iron levels already in the normal range*", "A building block of IronWoman wellness combos*"],
  },
  {
    slug: "gut-health-ironwoman",
    name: "Gut Health + IronWoman™",
    sku: "K1-GHI-0001",
    category: "womens-health",
    retail: 184,
    vip: 140,
    pv: 157,
    vipPv: 120,
    image: I.kit,
    kind: "combo",
    form: "Combo",
    glutenFree: true,
    blurb: "The Gut Health System paired with IronWoman™ for comprehensive inside-out women’s wellness.",
    benefits: ["Microbiome care plus gentle iron support*", "A complete daily routine for women*"],
    included: ["Gut Health System – Bio Cleanse® 60", "IronWoman™"],
  },
  {
    slug: "creatine-active-combo",
    name: "Creatine + and Active Lifestyle Combo",
    sku: "K1-CAL-0001",
    category: "active-lifestyle",
    retail: 185,
    vip: 139,
    pv: 143,
    vipPv: 108,
    image: I.active,
    kind: "combo",
    form: "Combo",
    glutenFree: true,
    blurb: "Performance, hydration, and clean energy in one active-lifestyle stack.",
    benefits: ["Supports training, hydration, and daily energy*", "Built around Creatine +, Active, and Hydrate*"],
    included: ["Creatine +", "Active", "Hydrate"],
  },
  {
    slug: "favorites-variety-pack",
    name: "Plexus® Favorites Variety Pack",
    sku: "P1-FVP-0001",
    category: "combos",
    retail: 16,
    vip: 12,
    pv: 10,
    vipPv: 8,
    image: I.promo,
    kind: "combo",
    form: "Sampler",
    blurb: "Taste the favorites — a low-commitment way to try Plexus drink mixes.",
    benefits: ["Sample iconic Plexus flavors*", "Perfect for sharing or first sips*"],
  },
];

export const categoryCopy: Record<CategorySlug, { title: string; lede: string }> = {
  "gut-health": {
    title: "Gut Health",
    lede: "Founded in gut health. Cleanse, feed, and seed your microbiome with the systems that started it all.",
  },
  "weight-management": {
    title: "Weight Management",
    lede: "Clinically studied Slim, Reset, and metabolic support — so you can feel lighter from the inside out.",
  },
  "skin-health": {
    title: "Skin Health",
    lede: "Beauty from within and a complete topical ritual. Your skin’s favorite sale starts here.",
  },
  "active-lifestyle": {
    title: "Active Lifestyle",
    lede: "Hydrate, Active, Creatine +, and Lean — clean fuel for the way you move.",
  },
  "general-nutrition": {
    title: "General Nutrition",
    lede: "Fill the gaps with Superfoods, MegaX, XFactor+, Immune+, and daily essentials.",
  },
  "womens-health": {
    title: "Women's Health",
    lede: "IronWoman™ and targeted combos designed around women’s wellness goals.",
  },
  "family-nutrition": {
    title: "Family Nutrition",
    lede: "Get the Health and Happiness your family deserves — products loved by kids and adults.",
  },
  combos: {
    title: "Combos",
    lede: "Save when you stack. Systems and pairings built to work better together.",
  },
};

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function productsIn(slug: CategorySlug | "all") {
  if (slug === "all") return products;
  if (slug === "combos") return products.filter((p) => p.kind === "combo");
  return products.filter((p) => p.category === slug);
}

export function featuredProducts() {
  return products.filter((p) => p.featured);
}

export function searchProducts(q: string) {
  const n = q.trim().toLowerCase();
  if (!n) return products;
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(n) ||
      p.blurb.toLowerCase().includes(n) ||
      p.sku.toLowerCase().includes(n) ||
      p.category.includes(n),
  );
}

export function relatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.slug !== product.slug && (p.category === product.category || p.kind === product.kind))
    .slice(0, limit);
}
