/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as GuaranteeRouteImport } from './routes/guarantee'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteeRoute = GuaranteeRouteImport.update({
  id: '/guarantee',
  path: '/guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/experience': typeof ExperienceRoute
  '/guarantee': typeof GuaranteeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/resources': typeof ResourcesRoute
  '/shop': typeof ShopRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/experience': typeof ExperienceRoute
  '/guarantee': typeof GuaranteeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/resources': typeof ResourcesRoute
  '/shop': typeof ShopRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/experience': typeof ExperienceRoute
  '/guarantee': typeof GuaranteeRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/resources': typeof ResourcesRoute
  '/shop': typeof ShopRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/experience'
    | '/guarantee'
    | '/help'
    | '/join'
    | '/login'
    | '/reset'
    | '/resources'
    | '/shop'
    | '/product/$slug'
    | '/shop/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/experience'
    | '/guarantee'
    | '/help'
    | '/join'
    | '/login'
    | '/reset'
    | '/resources'
    | '/shop'
    | '/product/$slug'
    | '/shop/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/experience'
    | '/guarantee'
    | '/help'
    | '/join'
    | '/login'
    | '/reset'
    | '/resources'
    | '/shop'
    | '/product/$slug'
    | '/shop/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ExperienceRoute: typeof ExperienceRoute
  GuaranteeRoute: typeof GuaranteeRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  ResourcesRoute: typeof ResourcesRoute
  ShopRoute: typeof ShopRouteWithChildren
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantee': {
      id: '/guarantee'
      path: '/guarantee'
      fullPath: '/guarantee'
      preLoaderRoute: typeof GuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopCategoryRoute: typeof ShopCategoryRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCategoryRoute: ShopCategoryRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ExperienceRoute: ExperienceRoute,
  GuaranteeRoute: GuaranteeRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  ResourcesRoute: ResourcesRoute,
  ShopRoute: ShopRouteWithChildren,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
